--Accounts table
SET QUOTED_IDENTIFIER ON;
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Accounts' and xtype='U')
BEGIN
	CREATE TABLE Accounts(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL, 
	CompanyCode VARCHAR(50) NOT NULL, 
	AccountOwner VARCHAR(50) NOT NULL,
	Balance DECIMAL NOT NULL DEFAULT 0,
	AccountStatus INT NULL,
	CountingType INT NULL,
	ActivatedBy VARCHAR(MAX) NULL, 
	CreatedBy VARCHAR(MAX) NOT NULL, 
	DeactivatedBy VARCHAR(MAX) NULL, 
	WorkDayHours INT NULL, 
	HourlyRate DECIMAL NULL, 
	OvertimeRate DECIMAL NULL,  
	IsActive BIT NOT NULL,
	ExpirationDate DATETIME NULL, 
	SettlementDayMonth INT NULL,
	PayoutAmount DECIMAL NULL,
	Created DATETIME DEFAULT GETDATE(),
	Modified DATETIME DEFAULT GETDATE()
) 
END

--Settlements table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Settlements' and xtype='U')
BEGIN
	CREATE TABLE Settlements(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	AccountId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Accounts(Id), 
	[From] DATETIME NOT NULL,
	[To] DATETIME NOT NULL,
	[Value] DATETIME NOT NULL,
	Created DATETIME DEFAULT GETDATE(),
	Modified DATETIME DEFAULT GETDATE()
) 
END


--WorkDays table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='WorkDays' and xtype='U')
BEGIN
	CREATE TABLE WorkDays(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	AccountId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Accounts(Id),
	[Date] DATETIME NOT NULL,
	HoursWorked INT NOT NULL,
	Overtime INT DEFAULT 0,
	IsDayOff BIT DEFAULT 0,  
	CreatedBy VARCHAR(MAX) NOT NULL,
	Created DATETIME DEFAULT GETDATE(),
	Modified DATETIME DEFAULT GETDATE()
) 
END

--Bonuses table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Bonuses' and xtype='U')
BEGIN
	CREATE TABLE Bonuses(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(), 
	AccountId UNIQUEIDENTIFIER NOT NULL REFERENCES Accounts(Id),  
	BonusCode VARCHAR(12) NOT NULL, 
	Amount DECIMAL NOT NULL,
	Creator VARCHAR(MAX) NOT NULL,
	Settled BIT NOT NULL DEFAULT 0,
	Canceled BIT NOT NULL DEFAULT 0,
	Created DATETIME DEFAULT GETDATE(),
	Modified DATETIME DEFAULT GETDATE(), 
) 
END

--PieceworkProducts table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PieceworkProducts' and xtype='U')
BEGIN
	CREATE TABLE PieceworkProducts(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL, 
	CompanyCode VARCHAR(50) NOT NULL,
	ProductSku VARCHAR(12) NOT NULL,
	PricePerUnit DECIMAL NOT NULL,
	CountedInUnit VARCHAR(50) NOT NULL,
	ProductName VARCHAR(50) NOT NULL,
	IsAvailable BIT NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	Created DATETIME DEFAULT GETDATE(),
	Modified DATETIME DEFAULT GETDATE(),
) 

--TYPE
		
		CREATE TYPE [dbo].[ConsiderationTableType] AS TABLE
		(
			Id UNIQUEIDENTIFIER NOT NULL 
		)
END

--ProductPriceHistory
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ProductPriceHistory' and xtype='U')
BEGIN
	CREATE TABLE ProductPriceHistory(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),  
	ProductId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES PieceworkProducts(Id) ON DELETE CASCADE,
	Price DECIMAL,
	Created DATETIME DEFAULT GETDATE()
)
END


--ProductItems table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ProductItems' and xtype='U')
BEGIN
	CREATE TABLE ProductItems(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	AccountId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Accounts(Id),
	PieceworkProductId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES PieceworkProducts(Id),
	CurrentPrice DECIMAL NOT NULL,
	Quantity DECIMAL NOT NULL,
	IsConsidered BIT NOT NULL DEFAULT 0,
	[Date] DATETIME NOT NULL,
	Created DATETIME DEFAULT GETDATE(),
	Modified DATETIME DEFAULT GETDATE()
) 
END
