on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
      - '*/Calculator*'
      - '*/Management*'

env: 
  CALCULATOR_TESTS_PATH: 'src/Services/Calculator/Tests/Calculator.UnitTests/Calculator.UnitTests.csproj'
  MANAGEMENT_TESTS_PATH: 'src/Services/Management/Tests/Management.UnitTests/Management.UnitTests.csproj'

jobs:
  calculator-tests:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.head_ref || github.ref_name, 'Calculator' ) }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore TeamTitanMicroservices.sln
      - name: Build
        run: dotnet build TeamTitanMicroservices.sln --no-restore
      - name: Run Calculator Service Tests
        if: ${{ contains(github.head_ref, 'Calculator') }}
        run: dotnet test ${{ env.CALCULATOR_TESTS_PATH }}
        
  management-tests:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.head_ref || github.ref_name, 'Management' ) }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore TeamTitanMicroservices.sln
      - name: Build
        run: dotnet build TeamTitanMicroservices.sln --no-restore
      - name: Run Management Service Tests
        if: ${{ contains(github.head_ref, 'Management') }}
        run: dotnet test ${{ env.MANAGEMENT_TESTS_PATH }}        
