on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
      - '*/Calculator*'

env: 
  CALCULATOR_TESTS_PATH: 'src/Services/Calculator/Tests/Calculator.UnitTests/Calculator.UnitTests.csproj'

jobs:
  calculator-tests:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'Calculator*')
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore TeamTitanMicroservices.sln
      - name: Build
        run: dotnet build TeamTitanMicroservices.sln --no-restore
      - name: Run Calculator Service Tests
        if: ${{ contains(github.head_ref, 'Calculator') }}
        run: dotnet test ${{ env.CALCULATOR_TESTS_PATH }}
